# CLI tools
brew "bat"
brew "eza"
brew "fzf"
brew "git"
brew "gh"
brew "just"
brew "pnpm"
brew "ripgrep"
brew "zsh-syntax-highlighting"

# Apps
cask "1password"
cask "docker-desktop"
cask "ghostpepper"
cask "ghostty"
cask "hiddenbar"
cask "logi-options+"
cask "meetingbar"
cask "postgres-app"
cask "raycast"
cask "tableplus"
cask "visual-studio-code"
cask "zed"
